markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: false
      xHTML: false
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - ['$$', '$$']
            - ['\\[', '\\]']
          inline:
            - ['$', '$']
            - ['\\(', '\\)']
  highlight:
    style: 'github-dark'
    lineNos: true
    lineNumbersInTable: true
    guessSyntax: true
    noClasses: false
    tabWidth: 4
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false
  linkify: true
  typographer: true