menus:
  main:
    - name: 'Explore'
      weight: 10
      children:
        - name: 'CS'
          url: '/articles/cs/'
          weight: 10
        - name: 'AI'
          url: '/articles/ai/'
          weight: 20
        - name: 'Maths'
          url: '/articles/maths/'
          weight: 30
        - name: 'Physics'
          url: '/articles/physics/'
          weight: 40

    - name: 'Reflect'
      weight: 20
      children:
        - name: 'Philosophy'
          url: '/tags/philosophy/'
          weight: 10
        - name: 'Spirituality'
          url: '/articles/spirituality/'
          weight: 20
        - name: 'Life'
          url: '/tags/life/'
          weight: 30
        - name: 'Sports'
          url: '/articles/sports/'
          weight: 40

    - name: 'Review'
      weight: 30
      children:
        - name: 'Movies'
          url: '/articles/reviews/movies/'
          weight: 10
        - name: 'Technology'
          url: '/articles/reviews/technology/'
          weight: 20
        - name: 'Books'
          url: '/articles/reviews/books/'
          weight: 30
        - name: 'Food'
          url: '/articles/reviews/food/'
          weight: 40
        - name: 'Places'
          url: '/articles/reviews/places/'
          weight: 50

    - name: 'About'
      weight: 40
      children:
        - name: 'Story'
          url: '/about/story/'
          weight: 10
        - name: 'Contact'
          url: '/about/contact/'
          weight: 20

    - name: 'Search'
      url: '/search/'
      weight: 100

  social:
    - name: 'GitHub'
      url: 'https://github.com/arunkumarvenkitaraman'
      weight: 10
    - name: 'LinkedIn'
      url: 'https://linkedin.com/in/arunkumarvenkitaraman'
      weight: 20
    - name: 'Email'
      url: 'mailto:arun@akscape.com'
      weight: 30

  footer:
    - name: 'Explore'
      weight: 10
      children:
        - name: 'CS'
          url: '/articles/cs/'
          weight: 10
        - name: 'AI'
          url: '/articles/ai/'
          weight: 20
        - name: 'Maths'
          url: '/articles/maths/'
          weight: 30
        - name: 'Physics'
          url: '/articles/physics/'
          weight: 40

    - name: 'Reflect'
      weight: 20
      children:
        - name: 'Philosophy'
          url: '/tags/philosophy/'
          weight: 10
        - name: 'Spirituality'
          url: '/articles/spirituality/'
          weight: 20
        - name: 'Life'
          url: '/tags/life/'
          weight: 30
        - name: 'Sports'
          url: '/articles/sports/'
          weight: 40

    - name: 'Review'
      weight: 30
      children:
        - name: 'Movies'
          url: '/articles/reviews/movies/'
          weight: 10
        - name: 'Technology'
          url: '/articles/reviews/technology/'
          weight: 20
        - name: 'Books'
          url: '/articles/reviews/books/'
          weight: 30
        - name: 'Food'
          url: '/articles/reviews/food/'
          weight: 40
        - name: 'Places'
          url: '/articles/reviews/places/'
          weight: 50

    - name: 'About'
      weight: 40
      children:
        - name: 'Story'
          url: '/about/story/'
          weight: 10
        - name: 'Contact'
          url: '/about/contact/'
          weight: 20

    - name: 'Connect'
      weight: 50
      children:
        - name: 'GitHub'
          url: 'https://github.com/arunkumarvenkitaraman'
          weight: 10
        - name: 'LinkedIn'
          url: 'https://linkedin.com/in/arunkumarvenkitaraman'
          weight: 20
        - name: 'Email'
          url: 'mailto:arun@akscape.com'
          weight: 30

    - name: '© 2024 Arun Kumar Venkitaraman'
      weight: 100